apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: default
type: Opaque
data:
  # Base64 encoded docker config
  # To create: echo -n '{"auths":{}}' | base64
  config.json: e30K
